# @package _global_
# model parameters

has_overrides: True
# POLICY model
policy_cfg:
  embedding_dim: 128

  node_encoder_args:
    hidden_dim: 128
    num_layers: 3
    conv_type: "GATv2Conv"
    add_self_loops: False
    edge_dim: 1
    heads: 2
    concat: False

  tour_encoder_args:
    hidden_dim: 128
    num_layers: 2
    conv_type: "GATv2Conv"
    add_self_loops: False
    edge_dim: 1
    heads: 2
    concat: False
