# @package _global_
# model parameters

has_overrides: True
# POLICY model
policy_cfg:
  embedding_dim: 256

  node_encoder_args:
    hidden_dim: 128
    num_layers: 3
    conv_type: "GraphConv"

  tour_encoder_args:
    hidden_dim: 128
    num_layers: 2
    conv_type: "GraphConv"

