# @package _global_
# primary config file for experiments

defaults:
  - _self_
  - search: default
  - env_cfg_overrides: K1
  - model: v1
  - override hydra/job_logging: file


hydra:
  # disable hydra output
  run:
    dir: .  #cur dir
  output_subdir: #None

  #
  # help flag output. customize for application
  help:
    # App name, override to match the name your app is known by
    app_name: ${hydra.job.name}.py - Run JAMPR+ LNS according to config.

    # Help header, customize to describe your app to your users
    header: |
      ${hydra.help.app_name}

    footer: |
      Use --hydra-help to view Hydra specific help

    template: |
      ${hydra.help.header}
      == Configuration groups ==
      Compose your configuration from those groups (group=option)

      $APP_CONFIG_GROUPS

      == Config ==
      Override anything in the config (foo.bar=value)

      $CONFIG

      ${hydra.help.footer}
